# Generated by Django 3.2.23 on 2024-01-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
